In [1]:
import numpy as np
np.random.seed(1981)

In [2]:
arr = np.random.normal(0,1,100)

In [12]:
b = (arr > 0)arr[]

In [13]:
arr.nbytes

800

In [15]:
arr[b]

array([ 1.7255197 ,  1.06330152,  2.12567684,  0.32074305,  1.53789072,
        0.49380604,  0.2004674 ,  0.75590369,  0.65364312,  1.00156045,
        0.65888887,  0.69565833,  0.01801118,  0.9901191 ,  1.13571308,
        1.15928378,  0.14507436,  0.65855472,  0.23888984,  1.12632098,
        0.30167131,  0.76719563,  0.98457033,  0.00512749,  0.6906881 ,
        1.78095431,  0.41397943,  0.75570867,  0.65686019,  0.79039655,
        0.6267854 ,  1.09373525,  0.07108062,  1.04674676,  0.26901663,
        0.56443296,  1.72374411,  0.35367007,  1.23447707,  1.46118112,
        0.34508151,  1.22905208,  1.14313494,  0.09555944,  0.66186891,
        0.28065873,  2.41411693,  0.30437778,  0.53005835,  0.34600342,
        1.52107406,  1.03242432,  0.51758303,  1.68614647,  1.96076171,
        0.83396644])

In [16]:
arr[arr<0]

array([ -3.16804931e-01,  -4.88962319e-01,  -1.00148437e+00,
        -9.55745726e-01,  -6.28474290e-01,  -1.54042042e+00,
        -6.58233503e-01,  -9.04523450e-01,  -1.12702031e+00,
        -3.21548967e-01,  -5.99345682e-01,  -1.92691071e-01,
        -8.81770526e-01,  -7.73525377e-02,  -4.80384621e-01,
        -1.71024927e+00,  -1.27272050e+00,  -1.29894177e-04,
        -1.50590317e-01,  -6.59364833e-01,  -1.23103387e+00,
        -2.92885680e-01,  -5.93305697e-01,  -7.51495651e-01,
        -8.56878053e-02,  -1.78592391e-01,  -1.49354926e+00,
        -6.56501801e-01,  -1.12200332e-01,  -2.24423561e+00,
        -2.18782682e-01,  -1.15444886e+00,  -5.18799923e-02,
        -7.24343015e-01,  -1.04167445e+00,  -3.05180951e+00,
        -9.35121313e-01,  -8.36256808e-02,  -3.54106747e-02,
        -1.67327071e-02,  -1.95977889e-01,  -1.53661002e+00,
        -9.93075363e-01,  -4.09008433e-01])

In [31]:
(arr >0 ) | (arr*2 > 4)

array([False, False,  True, False,  True,  True, False,  True, False,
        True,  True,  True,  True, False, False,  True, False, False,
       False,  True, False, False, False,  True,  True,  True,  True,
       False, False,  True,  True,  True, False,  True,  True,  True,
        True, False, False,  True, False,  True, False, False,  True,
       False,  True,  True,  True,  True,  True,  True, False, False,
        True,  True,  True,  True,  True, False,  True,  True, False,
       False, False,  True, False,  True,  True, False,  True,  True,
        True, False, False,  True, False,  True, False, False,  True,
       False, False,  True, False, False, False, False,  True, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [18]:
arr[(arr >0 ) & (arr*2 > 4)]

array([ 2.12567684,  2.41411693])

In [19]:
# & = and,  = not, | = or,  = xor??

In [28]:
(arr >0 ) !& (arr*2 > 4)

SyntaxError: invalid syntax (<ipython-input-28-75787bd3aaf6>, line 1)

In [24]:
ap = arr >0
an = arr <0
p2 = np.abs(arr) >0.5



In [37]:
big = np.random.normal(0,1,int(1e8))
big.nbytes / 1e7

80.0

In [39]:
%time
ap = big >0
an = big < 0
p2 = np.abs(big) >0.5

Wall time: 0 ns


In [40]:
ap

array([ True, False, False, ..., False,  True, False], dtype=bool)

In [41]:
an

array([False,  True,  True, ...,  True, False,  True], dtype=bool)

In [42]:
ap|an

array([ True,  True,  True, ...,  True,  True,  True], dtype=bool)

In [43]:
len(ap|an)

100000000

In [46]:
len(big[an|ap])

100000000

In [50]:
%timeit big[ap & p2]

1 loop, best of 3: 713 ms per loop


In [51]:
6 //2

3

In [52]:
6//4

1

In [53]:
5 | 4

5

In [54]:
5 && 2

SyntaxError: invalid syntax (<ipython-input-54-fe8d1b592ec6>, line 1)

In [55]:
5 & 2

0

In [56]:
5 & 5

5

In [57]:
arr[~(arr >0)]

array([ -3.16804931e-01,  -4.88962319e-01,  -1.00148437e+00,
        -9.55745726e-01,  -6.28474290e-01,  -1.54042042e+00,
        -6.58233503e-01,  -9.04523450e-01,  -1.12702031e+00,
        -3.21548967e-01,  -5.99345682e-01,  -1.92691071e-01,
        -8.81770526e-01,  -7.73525377e-02,  -4.80384621e-01,
        -1.71024927e+00,  -1.27272050e+00,  -1.29894177e-04,
        -1.50590317e-01,  -6.59364833e-01,  -1.23103387e+00,
        -2.92885680e-01,  -5.93305697e-01,  -7.51495651e-01,
        -8.56878053e-02,  -1.78592391e-01,  -1.49354926e+00,
        -6.56501801e-01,  -1.12200332e-01,  -2.24423561e+00,
        -2.18782682e-01,  -1.15444886e+00,  -5.18799923e-02,
        -7.24343015e-01,  -1.04167445e+00,  -3.05180951e+00,
        -9.35121313e-01,  -8.36256808e-02,  -3.54106747e-02,
        -1.67327071e-02,  -1.95977889e-01,  -1.53661002e+00,
        -9.93075363e-01,  -4.09008433e-01])

In [59]:
arr[(arr>0) ^ (np.abs(arr) > 0.5)]

array([-1.00148437, -0.95574573,  0.32074305, -0.62847429,  0.49380604,
        0.2004674 , -1.54042042, -0.6582335 , -0.90452345, -1.12702031,
       -0.59934568, -0.88177053,  0.01801118,  0.14507436, -1.71024927,
        0.23888984,  0.30167131, -1.2727205 , -0.65936483, -1.23103387,
        0.00512749,  0.41397943, -0.5933057 , -0.75149565,  0.07108062,
        0.26901663, -1.49354926, -0.6565018 ,  0.35367007, -2.24423561,
        0.34508151, -1.15444886,  0.09555944, -0.72434302, -1.04167445,
        0.28065873, -3.05180951, -0.93512131,  0.30437778, -1.53661002,
       -0.99307536,  0.34600342])

In [60]:
arr<<1

TypeError: ufunc 'left_shift' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [64]:
np.left_shift((arr >0),1)

array([0, 0, 2, 0, 2, 2, 0, 2, 0, 2, 2, 2, 2, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0,
       2, 2, 2, 2, 0, 0, 2, 2, 2, 0, 2, 2, 2, 2, 0, 0, 2, 0, 2, 0, 0, 2, 0,
       2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 0, 2, 2, 0, 0, 0, 2, 0, 2, 2,
       0, 2, 2, 2, 0, 0, 2, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0,
       2, 2, 2, 2, 2, 2, 2, 2], dtype=int32)

In [65]:
arr >0

array([False, False,  True, False,  True,  True, False,  True, False,
        True,  True,  True,  True, False, False,  True, False, False,
       False,  True, False, False, False,  True,  True,  True,  True,
       False, False,  True,  True,  True, False,  True,  True,  True,
        True, False, False,  True, False,  True, False, False,  True,
       False,  True,  True,  True,  True,  True,  True, False, False,
        True,  True,  True,  True,  True, False,  True,  True, False,
       False, False,  True, False,  True,  True, False,  True,  True,
        True, False, False,  True, False,  True, False, False,  True,
       False, False,  True, False, False, False, False,  True, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

##Filtering

In [67]:
arr[arr>0] #subset, by not a view. Slicing and reshaping are views

array([ 1.7255197 ,  1.06330152,  2.12567684,  0.32074305,  1.53789072,
        0.49380604,  0.2004674 ,  0.75590369,  0.65364312,  1.00156045,
        0.65888887,  0.69565833,  0.01801118,  0.9901191 ,  1.13571308,
        1.15928378,  0.14507436,  0.65855472,  0.23888984,  1.12632098,
        0.30167131,  0.76719563,  0.98457033,  0.00512749,  0.6906881 ,
        1.78095431,  0.41397943,  0.75570867,  0.65686019,  0.79039655,
        0.6267854 ,  1.09373525,  0.07108062,  1.04674676,  0.26901663,
        0.56443296,  1.72374411,  0.35367007,  1.23447707,  1.46118112,
        0.34508151,  1.22905208,  1.14313494,  0.09555944,  0.66186891,
        0.28065873,  2.41411693,  0.30437778,  0.53005835,  0.34600342,
        1.52107406,  1.03242432,  0.51758303,  1.68614647,  1.96076171,
        0.83396644])

In [108]:
a1  =np.random.randint(0,10,100).reshape((10,10))

In [109]:
a1

array([[8, 1, 1, 6, 0, 5, 8, 9, 6, 7],
       [9, 1, 1, 6, 9, 2, 0, 2, 0, 0],
       [9, 7, 8, 3, 9, 7, 3, 5, 2, 3],
       [9, 3, 0, 3, 8, 9, 6, 0, 4, 9],
       [7, 3, 1, 6, 1, 8, 0, 7, 3, 3],
       [7, 7, 7, 4, 0, 8, 2, 0, 8, 9],
       [8, 4, 7, 4, 7, 2, 0, 7, 9, 8],
       [7, 8, 2, 7, 6, 3, 7, 5, 3, 3],
       [4, 4, 4, 0, 5, 6, 6, 8, 2, 6],
       [7, 7, 4, 0, 9, 2, 2, 3, 7, 3]])

In [74]:
arr4[::2]

array([[5, 4, 9, 3],
       [8, 7, 0, 1]])

In [99]:
arr

array([ -3.16804931e-01,  -4.88962319e-01,   1.72551970e+00,
        -1.00148437e+00,   1.06330152e+00,   2.12567684e+00,
        -9.55745726e-01,   3.20743053e-01,  -6.28474290e-01,
         1.53789072e+00,   4.93806036e-01,   2.00467399e-01,
         7.55903687e-01,  -1.54042042e+00,  -6.58233503e-01,
         6.53643119e-01,  -9.04523450e-01,  -1.12702031e+00,
        -3.21548967e-01,   1.00156045e+00,  -5.99345682e-01,
        -1.92691071e-01,  -8.81770526e-01,   6.58888871e-01,
         6.95658334e-01,   1.80111815e-02,   9.90119098e-01,
        -7.73525377e-02,  -4.80384621e-01,   1.13571308e+00,
         1.15928378e+00,   1.45074363e-01,  -1.71024927e+00,
         6.58554717e-01,   2.38889836e-01,   1.12632098e+00,
         3.01671307e-01,  -1.27272050e+00,  -1.29894177e-04,
         7.67195633e-01,  -1.50590317e-01,   9.84570334e-01,
        -6.59364833e-01,  -1.23103387e+00,   5.12749335e-03,
        -2.92885680e-01,   6.90688102e-01,   1.78095431e+00,
         4.13979430e-01,

In [105]:
import numpy as np

In [104]:
aa

NameError: name 'aa' is not defined

In [79]:
a[2,2]

0

In [81]:
a[::2,::2]

array([[5, 9],
       [8, 0]])

In [88]:
a[1::2,1::2]

array([[2, 3],
       [7, 2]])

In [97]:
def pyramid(a):
    b = (a[::2,::2] +a[::2,1::2]+a[1::2,::2]+a[1::2,1::2])/4
    return b

d = pyramid(arr4)

In [111]:
pyramid(a1)

array([[ 4.75,  3.5 ,  4.  ,  4.75,  3.25],
       [ 7.  ,  3.5 ,  8.25,  3.5 ,  4.5 ],
       [ 6.  ,  4.5 ,  4.25,  2.25,  5.75],
       [ 6.75,  5.  ,  4.5 ,  4.75,  5.75],
       [ 5.5 ,  2.  ,  5.5 ,  4.75,  4.5 ]])