In [1]:
import numpy as np

In [2]:
np.random.seed(1981)

In [4]:
arr = np.random.randint(0,100,20)

In [5]:
arr

array([29, 89, 98, 27, 37, 79, 95, 62,  0, 46, 96, 21, 89, 79, 50, 69, 95,
       12, 85, 62])

In [6]:
arr[0]

29

In [8]:
arr[-1]

62

In [9]:
arr[0:5]

array([29, 89, 98, 27, 37])

In [10]:
arr[10:15]

array([96, 21, 89, 79, 50])

In [11]:
arr[10:15:2]

array([96, 89, 50])

In [12]:
arr[:,:,2]

IndexError: too many indices for array

In [13]:
arr[::2]
        

array([29, 98, 37, 95,  0, 96, 89, 50, 95, 85])

In [15]:
arr[15:5:-3]

array([69, 89, 46, 95])

In [16]:
arr[::-1]

array([62, 85, 12, 95, 69, 50, 79, 89, 21, 96, 46,  0, 62, 95, 79, 37, 27,
       98, 89, 29])

In [17]:
arr2 = arr.reshape((5,4))

In [18]:
arr2

array([[29, 89, 98, 27],
       [37, 79, 95, 62],
       [ 0, 46, 96, 21],
       [89, 79, 50, 69],
       [95, 12, 85, 62]])

In [19]:
!ls ./img

'ls' is not recognized as an internal or external command,
operable program or batch file.


In [20]:
!dir ./img

Invalid switch - "img".


In [21]:
!dir

 Volume in drive C has no label.
 Volume Serial Number is 5212-86FA

 Directory of C:\Users\student01\Desktop\training-course-introduction-adefusco-CapOne\notebooks

08/23/2016  10:56 AM    <DIR>          .
08/23/2016  10:56 AM    <DIR>          ..
08/23/2016  10:50 AM    <DIR>          .ipynb_checkpoints
08/23/2016  08:54 AM             6,759 boolean.ipynb
08/23/2016  08:54 AM            10,306 comprehensions.ipynb
08/23/2016  08:54 AM             3,214 comprehensions_ex.ipynb
08/23/2016  08:54 AM             3,810 comprehensions_soln.ipynb
08/23/2016  08:54 AM            21,030 conda.ipynb
08/23/2016  08:54 AM            28,618 containers.ipynb
08/23/2016  08:54 AM             3,655 containers_ex.ipynb
08/23/2016  08:54 AM             4,133 containers_soln.ipynb
08/23/2016  08:54 AM    <DIR>          data
08/23/2016  08:54 AM            24,100 datatypes.ipynb
08/23/2016  08:54 AM             5,878 datatypes_ex.ipynb
08/23/2016  08:54 AM             5,890 datatypes_soln.ipynb
08/23/20

In [22]:
arr2

array([[29, 89, 98, 27],
       [37, 79, 95, 62],
       [ 0, 46, 96, 21],
       [89, 79, 50, 69],
       [95, 12, 85, 62]])

In [23]:
arr2[1]

array([37, 79, 95, 62])

In [24]:
arr2[:1]

array([[29, 89, 98, 27]])

In [25]:
arr2

array([[29, 89, 98, 27],
       [37, 79, 95, 62],
       [ 0, 46, 96, 21],
       [89, 79, 50, 69],
       [95, 12, 85, 62]])

In [42]:
arr2[:,1]

array([89, 79, 46, 79, 12])

In [27]:
arr2[,:]

SyntaxError: invalid syntax (<ipython-input-27-24fd790d94fe>, line 1)

In [28]:
arr2[::2]

array([[29, 89, 98, 27],
       [ 0, 46, 96, 21],
       [95, 12, 85, 62]])

In [30]:
arr2[::2]

array([[29, 89, 98, 27],
       [ 0, 46, 96, 21],
       [95, 12, 85, 62]])

In [31]:
arr2[::2,:]

array([[29, 89, 98, 27],
       [ 0, 46, 96, 21],
       [95, 12, 85, 62]])

In [32]:
arr2

array([[29, 89, 98, 27],
       [37, 79, 95, 62],
       [ 0, 46, 96, 21],
       [89, 79, 50, 69],
       [95, 12, 85, 62]])

In [33]:
arr2[][2]

SyntaxError: invalid syntax (<ipython-input-33-c175a71ed305>, line 1)

In [34]:
arr2[:][2]

array([ 0, 46, 96, 21])

In [35]:
arr2[2]

array([ 0, 46, 96, 21])

In [37]:
arr2[-2:-2:]

array([], shape=(0, 4), dtype=int32)

In [40]:
arr2[-2:,-2:]

array([[50, 69],
       [85, 62]])

In [41]:
arr2[:,2]

array([98, 95, 96, 50, 85])

In [43]:
arr2[::-1]

array([[95, 12, 85, 62],
       [89, 79, 50, 69],
       [ 0, 46, 96, 21],
       [37, 79, 95, 62],
       [29, 89, 98, 27]])

In [47]:
arr2[::2,::2] **2

array([[ 841, 9604],
       [   0, 9216],
       [9025, 7225]])

# Views and Copies

In [50]:
arr2.flags.owndata

False

In [51]:
arr.flags.owndata

True

In [52]:
arr

array([29, 89, 98, 27, 37, 79, 95, 62,  0, 46, 96, 21, 89, 79, 50, 69, 95,
       12, 85, 62])

In [54]:
arr[0]=1000

In [55]:
arr

array([1000,   89,   98,   27,   37,   79,   95,   62,    0,   46,   96,
         21,   89,   79,   50,   69,   95,   12,   85,   62])

In [56]:
arr2

array([[1000,   89,   98,   27],
       [  37,   79,   95,   62],
       [   0,   46,   96,   21],
       [  89,   79,   50,   69],
       [  95,   12,   85,   62]])

In [60]:
arr2[::2,::2] = np.arange(6).reshape(3,2)**4

In [61]:
arr2

array([[  0,  89,   1,  27],
       [ 37,  79,  95,  62],
       [ 16,  46,  81,  21],
       [ 89,  79,  50,  69],
       [256,  12, 625,  62]])

In [62]:
arr

array([  0,  89,   1,  27,  37,  79,  95,  62,  16,  46,  81,  21,  89,
        79,  50,  69, 256,  12, 625,  62])

In [63]:
arr2

array([[  0,  89,   1,  27],
       [ 37,  79,  95,  62],
       [ 16,  46,  81,  21],
       [ 89,  79,  50,  69],
       [256,  12, 625,  62]])

In [64]:
type(arr2[2:4,1:2])

numpy.ndarray

In [65]:
### how to combine with conditional??
##how to use other values in an elements neighboring cell to change each cell

In [66]:
arr_small = np.arange(10000,10001)

In [70]:
arr_small = arr2[2:4,1:2]

In [71]:
arr_small[:] = np.arange(10000,10001)

In [72]:
arr2

array([[    0,    89,     1,    27],
       [   37,    79,    95,    62],
       [   16, 10000,    81,    21],
       [   89, 10000,    50,    69],
       [  256,    12,   625,    62]])

In [73]:
arr3 = arr.reshape(4,5).copy()

In [74]:
arr3

array([[    0,    89,     1,    27,    37],
       [   79,    95,    62,    16, 10000],
       [   81,    21,    89, 10000,    50],
       [   69,   256,    12,   625,    62]])

In [75]:
arr3.flags.owndata

True